from .resume_prompt import (
    PROMPT_NAME as RESUME_PROMPT_NAME,
    PROMPT_VERSION as RESUME_PROMPT_VERSION,
    SYSTEM_PROMPT as RESUME_SYSTEM_PROMPT,
    USER_PROMPT as RESUME_USER_PROMPT,
)

from .ats_prompt import (
    PROMPT_NAME as ATS_PROMPT_NAME,
    PROMPT_VERSION as ATS_PROMPT_VERSION,
    SYSTEM_PROMPT as ATS_SYSTEM_PROMPT,
    USER_PROMPT as ATS_USER_PROMPT,
)

from .placement_prompt import (
    PROMPT_NAME as PLACEMENT_PROMPT_NAME,
    PROMPT_VERSION as PLACEMENT_PROMPT_VERSION,
    SYSTEM_PROMPT as PLACEMENT_SYSTEM_PROMPT,
    USER_PROMPT as PLACEMENT_USER_PROMPT,
)

from .salary_prompt import (
    PROMPT_NAME as SALARY_PROMPT_NAME,
    PROMPT_VERSION as SALARY_PROMPT_VERSION,
    SYSTEM_PROMPT as SALARY_SYSTEM_PROMPT,
    USER_PROMPT as SALARY_USER_PROMPT,
)

from .career_prompt import (
    PROMPT_NAME as CAREER_PROMPT_NAME,
    PROMPT_VERSION as CAREER_PROMPT_VERSION,
    SYSTEM_PROMPT as CAREER_SYSTEM_PROMPT,
    USER_PROMPT as CAREER_USER_PROMPT,
)

from .interview_prompt import (
    PROMPT_NAME as INTERVIEW_PROMPT_NAME,
    PROMPT_VERSION as INTERVIEW_PROMPT_VERSION,
    SYSTEM_PROMPT as INTERVIEW_SYSTEM_PROMPT,
    USER_PROMPT as INTERVIEW_USER_PROMPT,
)

from .resume_optimizer_prompt import (
    PROMPT_NAME as RESUME_OPTIMIZER_PROMPT_NAME,
    PROMPT_VERSION as RESUME_OPTIMIZER_PROMPT_VERSION,
    SYSTEM_PROMPT as RESUME_OPTIMIZER_SYSTEM_PROMPT,
    USER_PROMPT as RESUME_OPTIMIZER_USER_PROMPT,
)

from .resume_builder_prompt import (
    PROMPT_NAME as RESUME_BUILDER_PROMPT_NAME,
    PROMPT_VERSION as RESUME_BUILDER_PROMPT_VERSION,
    SYSTEM_PROMPT as RESUME_BUILDER_SYSTEM_PROMPT,
    USER_PROMPT as RESUME_BUILDER_USER_PROMPT,
)

from .job_matching_prompt import (
    PROMPT_NAME as JOB_MATCHING_PROMPT_NAME,
    PROMPT_VERSION as JOB_MATCHING_PROMPT_VERSION,
    SYSTEM_PROMPT as JOB_MATCHING_SYSTEM_PROMPT,
    USER_PROMPT as JOB_MATCHING_USER_PROMPT,
)

from .chat_prompt import (
    PROMPT_NAME as CHAT_PROMPT_NAME,
    PROMPT_VERSION as CHAT_PROMPT_VERSION,
    SYSTEM_PROMPT as CHAT_SYSTEM_PROMPT,
    USER_PROMPT as CHAT_USER_PROMPT,
)

from .json_repair_prompt import (
    PROMPT_NAME as JSON_REPAIR_PROMPT_NAME,
    PROMPT_VERSION as JSON_REPAIR_PROMPT_VERSION,
    SYSTEM_PROMPT as JSON_REPAIR_SYSTEM_PROMPT,
    USER_PROMPT as JSON_REPAIR_USER_PROMPT,
)